language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-cMoronb
  api_key:
    secure: LbVglJTG3XtrCiONSgnvTYoczkre/I+JesO61jiFDBVfMxnMbKINQ+Bz+/JMJJsbdNGVAfRwk58vYamNnCp2PRREQqjcIhtEfgldhFQGANXnPgc+c6XTrWF3E6CXLV/zg7PoZuBfJNqu+VK+z/WTJEWYdKPDUK5HGaTeSzAHCV+vUlEK5G2+0G1Tk2Y8xzty/mtZVUR9xTXtueKfHQjN4nSyJRW/30ckza/dk+peYhjkQ9Maa3Z0rorGcmNnbi3Wjm6DEJjJiwn4Ynoor2X1jJClV0WQ5fHcus9VeY7kAP8MNidz0DT9Y5WQMRAgvAVsGh3Ekno3hHGC9HInb8jaM4kKhpJ16J2CrQd2j7PvgdHBiGD9h2ohwmzz/Z3jGwoKZKiOeYjC5/a0c7f6uBGmqjRZEA7EwkDFq7K46sD0DlX5N880JHFXfRyp6kKKmBsG6RuSpP1kLV/AXHWYk1w2YIxQMuf3UK/OGvwNRyZsFhzIXHKiF/oF529WE1bWPDc1ef/xqqlmzcc0viTUBKgrgdDhjJpymLreA9Ky6Wf3JE9omn8bE+CeusfRfc33VxmIbzpy13MyeESTPwf+f28+7aX9+CZAu1kHEzQx4h6tzeErt9+xknIBTvKFSPT3CTMi6iXxRNbzb3IbABhkdb0D+aFsPyyg3uTJLzvDbkDph8c=
