language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-cmoronb
  api_key:
    secure: aYb3dnWbt6TlHjBlUDMS7QG3wfNMoEBLelAWLX2NBFbc0qjmzpN8dSdgfrgtzecTS4GrTwx6/GIS7c+9OvwUPUNvE+kYF3xGtmAu2i++6qZGV5TAa7PLfXY14q6gcZdFGd+RD/V/S3w0b1JsR96d7a1ntYsM19U6gboic63OR6/QGIo6G2xGwzpXrPjH0lOua4q+qffrdF6QDnWoJuozdSN7R9pFOzpinJYVpmLrGwjTg2FFdPfYp5hAFcZfG/jWCR6MxYTfRQDORof8DVejThmL0S7dFMgXvkmACJDw8TpRm7RXwuyRgOhS7uHoZ3+4HGTa0185ElztauRzWcEsCMDwY7dA03tOZQj5arhCy9HczkRcuyTvdqb65yNOkM9/DyhTcjQZNdr8/VDwtm3URAblPJyG/SNBozRcHHduMFFXwDtjRpuv7B541rnTwN1eCdKwga8zFYtkih9LxFZpPoFppt1jUecGWzbjLg9kQhK43aVMG+qj+tkrW4+pa21dsaWBfnIIH5zz8Ar3MtsEoR3n4UoDHWMEIYP6jEvgGOXPoVvXkhE9+PqgU0tITSlYkUDo6ocupSoGo75JX22zAngOkvLeErdGc9G0SMULcoHY3ZkAki53fApUVCfH1ZR3zEFoA4BYzNU2anZd0ez0S2YxSEDiFQRmqcXKP6cHUDA=
